[Postgres]
user = "server"
Pass = "password"
Database = "balance_api"
IP = "127.0.0.1"
Port = 5432

[Redis]
Address = "0.0.0.0:6379"
Pass = "password"
DB = 0
HashMap= "currency"

[Host]
Addr = "0.0.0.0"
Port = 8080
Key = "certs/localhost.key"
Cert = "certs/localhost.crt"