basePath: api/v1
definitions:
  dto.ChangeBalanceIN:
    properties:
      change:
        type: integer
      description:
        type: string
      user_id:
        type: integer
    type: object
  dto.ChangeBalanceOUT:
    properties:
      ok:
        type: boolean
    type: object
  dto.Error:
    properties:
      err:
        type: string
      ok:
        type: boolean
    type: object
  dto.GetBalanceIN:
    properties:
      base:
        type: string
      user_id:
        type: integer
    type: object
  dto.GetBalanceOUT:
    properties:
      balance:
        items:
          type: integer
        type: array
      base:
        type: string
      ok:
        type: boolean
    type: object
  dto.TransferBalanceIN:
    properties:
      amount:
        type: integer
      description:
        type: string
      from_id:
        type: integer
      to_id:
        type: integer
    type: object
  dto.TransferBalanceOUT:
    properties:
      ok:
        type: boolean
    type: object
  dto.ViewTransactionsIN:
    properties:
      limit:
        type: integer
      offset:
        type: integer
      sort:
        type: string
      user_id:
        type: integer
    required:
    - sort
    type: object
  dto.ViewTransactionsOUT:
    properties:
      ok:
        type: boolean
      transactions:
        items:
          $ref: '#/definitions/entity.Transaction'
        type: array
    type: object
  entity.Transaction:
    properties:
      action:
        type: integer
      date:
        type: string
      description:
        type: string
      from_id:
        description: number or "null"
        items:
          type: integer
        type: array
      to_id:
        type: integer
      transaction_id:
        type: integer
    type: object
host: 0.0.0.0:8080/
info:
  contact:
    email: illiadimura@gmail.com
    name: Developer
    url: https://github.com/illiafox
  description: Balance API.
  license:
    name: Boost Software License 1.0
    url: https://opensource.org/licenses/BSL-1.0
  termsOfService: https://swagger.io/terms/
  title: Balance API
  version: "1.0"
paths:
  /change:
    post:
      consumes:
      - application/json
      description: Change balance by user ID
      parameters:
      - description: User id, change amount and description
        in: body
        name: input
        schema:
          $ref: '#/definitions/dto.ChangeBalanceIN'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ChangeBalanceOUT'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Error'
        "406":
          description: Not Acceptable
          schema:
            $ref: '#/definitions/dto.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: Change user balance
      tags:
      - balance
  /get:
    get:
      consumes:
      - application/json
      description: Get balance by user ID
      parameters:
      - description: User id and Currency
        in: body
        name: input
        schema:
          $ref: '#/definitions/dto.GetBalanceIN'
      produces:
      - application/json
      responses:
        "200":
          description: Balance data
          schema:
            allOf:
            - $ref: '#/definitions/dto.GetBalanceOUT'
            - properties:
                balance:
                  type: integer
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/dto.Error'
        "406":
          description: Not Acceptable
          schema:
            $ref: '#/definitions/dto.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: Get user balance
      tags:
      - balance
  /transfer:
    put:
      consumes:
      - application/json
      description: Transfer money from one balance to another
      parameters:
      - description: to, from, amount and description
        in: body
        name: input
        schema:
          $ref: '#/definitions/dto.TransferBalanceIN'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.TransferBalanceOUT'
        "406":
          description: Not Acceptable
          schema:
            $ref: '#/definitions/dto.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: Transfer money between users
      tags:
      - balance
  /view:
    get:
      consumes:
      - application/json
      description: View transactions with sorting and pagination
      parameters:
      - description: User id, limit, sorting and pagination
        in: body
        name: input
        schema:
          $ref: '#/definitions/dto.ViewTransactionsIN'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.ViewTransactionsOUT'
        "406":
          description: Not Acceptable
          schema:
            $ref: '#/definitions/dto.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.Error'
      summary: View user transactions
      tags:
      - transactions
swagger: "2.0"
